# Generated by Django 4.1.2 on 2022-11-29 19:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyConsumed',
            fields=[
                ('dcid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('total_k', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_na', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_phos', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_water', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('systolic_bp', models.IntegerField(blank=True, default=0)),
                ('diastolic_bp', models.IntegerField(blank=True, default=0)),
                ('blood_glucose', models.IntegerField(blank=True, default=0)),
                ('mentalHealthRating', models.CharField(choices=[('Very Poor', 'Very Poor'), ('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Very Good', 'Very Good')], max_length=9)),
                ('goal_obtained', models.BooleanField()),
            ],
            options={
                'db_table': 'daily_consumed',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('food_K', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('food_na', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('food_phos', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('food_protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('food_water', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Target_Diet',
            fields=[
                ('diet_name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('protein_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('k_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('phos_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('water_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('na_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            options={
                'db_table': 'target_diet',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('age', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('comorbidity', models.CharField(choices=[('Diabetes', 'Diabetes'), ('High Blood Pressure', 'High Blood Pressure')], max_length=20)),
                ('diet_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtracker.target_diet')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='FoodConsumed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('dcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtracker.dailyconsumed')),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtracker.food')),
            ],
            options={
                'db_table': 'food_consumed',
            },
        ),
        migrations.AddField(
            model_name='dailyconsumed',
            name='consumedFood',
            field=models.ManyToManyField(through='foodtracker.FoodConsumed', to='foodtracker.food'),
        ),
        migrations.AddField(
            model_name='dailyconsumed',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtracker.person'),
        ),
    ]
