# Generated by Django 4.1.2 on 2022-12-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyconsumed',
            name='mentalHealthRating',
            field=models.CharField(choices=[('Very Poor', 'Very Poor'), ('Poor', 'Poor'), ('Fair', 'Fair'), ('Good', 'Good'), ('Very Good', 'Very Good')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='target_diet',
            name='diet_name',
            field=models.CharField(choices=[('3/4 Men', '3/4 Men'), ('3/4 Women', '3/4 Women'), ('Dialysis', 'Dialysis')], max_length=15, primary_key=True, serialize=False),
        ),
    ]
